[package]
name = "iced-2048"
version = "0.1.1"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0"
